-- ============================================================
-- 02_user_schema_ddl.sql
-- 스키마: SPEECHAPP_USER
-- 테이블: APP_USER, USER_PROFILE, TAGS, USER_PROFILE_TAGS,
--         USER_REPRESENTATIVE_SCORES
-- v2.0 (2026-09-04, D-1 / 04_Database_Design.md v2.2+v2.6):
--   USER_PROFILE 개편: likes → hobbies RENAME / age DROP /
--     birth_date DATE ADD / user_memory CLOB ADD
--   TAGS 신설 + 15종 시드 / USER_PROFILE_TAGS 신설 (복합 PK)
--   USER_REPRESENTATIVE_SCORES 신설 (대표점수 캐시 5종)
-- ============================================================

-- -----------------------------------------------------------
-- APP_USER
-- Oracle 예약어 USER를 피해 APP_USER 사용
-- 소셜 로그인 확장: social_provider + social_id (nullable)
-- ============================================================
CREATE TABLE speechapp_user.app_user (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR2(36)  NOT NULL UNIQUE,
    firebase_uid    VARCHAR2(255) UNIQUE,
    social_provider VARCHAR2(20),
    social_id       VARCHAR2(255) UNIQUE,
    email           VARCHAR2(255) UNIQUE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,

    -- 소셜 로그인 또는 일반 로그인 중 하나는 필수
    CONSTRAINT chk_app_user_login_method CHECK (
        (firebase_uid IS NOT NULL) OR (social_id IS NOT NULL)
    )
);

-- 인덱스
CREATE INDEX idx_app_user_uuid          ON speechapp_user.app_user(uuid);
CREATE INDEX idx_app_user_firebase_uid  ON speechapp_user.app_user(firebase_uid);
CREATE INDEX idx_app_user_social        ON speechapp_user.app_user(social_provider, social_id);

-- -----------------------------------------------------------
-- USER_PROFILE
-- APP_USER와 1:1 관계, user_id UNIQUE + FK
-- v2.2 가입 플로우 개편: hobbies(구 likes) / birth_date(구 age) /
--   user_memory CLOB (누적 개인화 메모리, 8KB 하드캡은 앱 레벨)
-- ============================================================
CREATE TABLE speechapp_user.user_profile (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             NUMBER(19) NOT NULL UNIQUE,
    nickname            VARCHAR2(50),
    profile_image_bucket_path VARCHAR2(500),
    hobbies             VARCHAR2(500),
    sex                 VARCHAR2(10),
    birth_date          DATE,
    user_memory         CLOB,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP,

    CONSTRAINT fk_user_profile_user_id
        FOREIGN KEY (user_id) REFERENCES speechapp_user.app_user(id)
);

-- -----------------------------------------------------------
-- TAGS (v2.2 신설) — 관심사 태그 마스터 15종
-- 가입 플로우 선택형 태그 (시니어 타겟), 최대 5개는 앱 레벨 검증
-- ============================================================
CREATE TABLE speechapp_user.tags (
    tag_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag         VARCHAR2(50) NOT NULL UNIQUE
);

-- -----------------------------------------------------------
-- USER_PROFILE_TAGS (v2.2 신설) — 유저↔태그 N:M
-- ============================================================
CREATE TABLE speechapp_user.user_profile_tags (
    user_id     NUMBER(19) NOT NULL,
    tag_id      NUMBER(19) NOT NULL,

    PRIMARY KEY (user_id, tag_id),

    CONSTRAINT fk_upt_user
        FOREIGN KEY (user_id) REFERENCES speechapp_user.app_user(id),
    CONSTRAINT fk_upt_tag
        FOREIGN KEY (tag_id) REFERENCES speechapp_user.tags(tag_id)
);

-- -----------------------------------------------------------
-- USER_REPRESENTATIVE_SCORES (v2.6 신설) — 대표점수 캐시 5종
-- 대시보드 방사형 그래프 + /sessions userAQ 전달용.
-- 갱신 지점 2곳 고정: 가입 설문 접수(USER_AQ 초기 세팅) +
--   /report/problems 수신(AQ+4지표 재계산 UPDATE)
-- LISTEN 지표 = LISTEN_TEXT/LISTEN_PICTURE 통합 (지표상 동일 LISTEN)
-- user_aq NULL = 설문 미응답 (설문 재노출 판별 기준)
-- ============================================================
CREATE TABLE speechapp_user.user_representative_scores (
    user_id             NUMBER(19) PRIMARY KEY,
    user_aq             NUMBER(3) CHECK (user_aq BETWEEN 0 AND 100),
    user_score_listen   NUMBER(5,2),
    user_score_naming   NUMBER(5,2),
    user_score_shadowing NUMBER(5,2),
    user_score_self_talk NUMBER(5,2),
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rep_scores_user FOREIGN KEY (user_id)
        REFERENCES speechapp_user.user_profile(user_id)
);

-- -----------------------------------------------------------
-- SEED DATA: TAGS 15종 (04_Database_Design.md §4.2.1 확정 순서)
-- ============================================================
INSERT INTO speechapp_user.tags (tag) VALUES ('건강관리');
INSERT INTO speechapp_user.tags (tag) VALUES ('등산');
INSERT INTO speechapp_user.tags (tag) VALUES ('골프');
INSERT INTO speechapp_user.tags (tag) VALUES ('여행');
INSERT INTO speechapp_user.tags (tag) VALUES ('트로트');
INSERT INTO speechapp_user.tags (tag) VALUES ('요리');
INSERT INTO speechapp_user.tags (tag) VALUES ('텃밭가꾸기');
INSERT INTO speechapp_user.tags (tag) VALUES ('낚시');
INSERT INTO speechapp_user.tags (tag) VALUES ('독서');
INSERT INTO speechapp_user.tags (tag) VALUES ('바둑');
INSERT INTO speechapp_user.tags (tag) VALUES ('사진');
INSERT INTO speechapp_user.tags (tag) VALUES ('전시관람');
INSERT INTO speechapp_user.tags (tag) VALUES ('국내여행');
INSERT INTO speechapp_user.tags (tag) VALUES ('반려동물');
INSERT INTO speechapp_user.tags (tag) VALUES ('봉사활동');

COMMIT;