-- ============================================================
-- 02_user_schema_ddl.sql
-- 스키마: SPEECHAPP_USER
-- 테이블: APP_USER, USER_PROFILE
-- ============================================================

-- -----------------------------------------------------------
-- APP_USER
-- Oracle 예약어 USER를 피해 APP_USER 사용
-- 소셜 로그인 확장: social_provider + social_id (nullable)
-- ============================================================
CREATE TABLE speechapp_user.app_user (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR2(36)  NOT NULL UNIQUE,
    firebase_uid    VARCHAR2(255) UNIQUE,
    social_provider VARCHAR2(20),
    social_id       VARCHAR2(255) UNIQUE,
    email           VARCHAR2(255) UNIQUE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,

    -- 소셜 로그인 또는 일반 로그인 중 하나는 필수
    CONSTRAINT chk_app_user_login_method CHECK (
        (firebase_uid IS NOT NULL) OR (social_id IS NOT NULL)
    )
);

-- 인덱스
CREATE INDEX idx_app_user_uuid          ON speechapp_user.app_user(uuid);
CREATE INDEX idx_app_user_firebase_uid  ON speechapp_user.app_user(firebase_uid);
CREATE INDEX idx_app_user_social        ON speechapp_user.app_user(social_provider, social_id);

-- -----------------------------------------------------------
-- USER_PROFILE
-- APP_USER와 1:1 관계, user_id UNIQUE + FK
-- -----------------------------------------------------------
CREATE TABLE speechapp_user.user_profile (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             NUMBER(19) NOT NULL UNIQUE,
    nickname            VARCHAR2(50),
    profile_image_url   VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP,

    CONSTRAINT fk_user_profile_user_id
        FOREIGN KEY (user_id) REFERENCES speechapp_user.app_user(id)
);
