-- ============================================================
-- 03_content_schema_ddl.sql
-- 스키마: SPEECHAPP_CONTENT
-- 테이블: IMAGE_RESOURCE, IMAGE_TAG, IMAGE_HINT
-- ============================================================

-- -----------------------------------------------------------
-- IMAGE_RESOURCE
-- Object Storage 메타데이터만 저장, 실제 파일은 Backend SDK가 관리
-- 게임 모드(DESCRIBE/CHOOSE)는 컬럼으로 강제하지 않음 —
-- IMAGE_TAG 존재 여부 → DESCRIBE 가능, IMAGE_HINT 존재 여부 → CHOOSE 가능
-- -----------------------------------------------------------
CREATE TABLE speechapp_content.image_resource (
    image_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_name      VARCHAR2(200) NOT NULL,
    bucket_path     VARCHAR2(500) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------
-- IMAGE_TAG
-- '그림 보고 설명하기' 정답 태그
-- -----------------------------------------------------------
CREATE TABLE speechapp_content.image_tag (
    tag_id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id        NUMBER(19) NOT NULL,
    tag_text        VARCHAR2(100) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_image_tag_image_id
        FOREIGN KEY (image_id) REFERENCES speechapp_content.image_resource(image_id)
);

CREATE INDEX idx_image_tag_image ON speechapp_content.image_tag(image_id);

-- -----------------------------------------------------------
-- IMAGE_HINT
-- '설명 보고 그림 맞추기' 힌트
-- -----------------------------------------------------------
CREATE TABLE speechapp_content.image_hint (
    hint_id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id        NUMBER(19) NOT NULL,
    hint_type       VARCHAR2(20)  NOT NULL,
    hint_text       VARCHAR2(200) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_image_hint_image_id
        FOREIGN KEY (image_id) REFERENCES speechapp_content.image_resource(image_id),
    CONSTRAINT chk_image_hint_type
        CHECK (hint_type IN ('CHOSUNG', 'ASSOCIATION'))
);

CREATE INDEX idx_image_hint_image ON speechapp_content.image_hint(image_id);
CREATE INDEX idx_image_hint_type  ON speechapp_content.image_hint(hint_type);
