-- ============================================================
-- 03_content_schema_ddl.sql
-- 스키마: SPEECHAPP_CONTENT
-- 테이블: IMAGE_RESOURCE, IMAGE_THEMA
-- ============================================================
-- v3 (2026-08-31):
--   IMAGE_TAG / IMAGE_HINT 테이블 제거 — 태그/힌트는 JSON 파일로
--   Object Storage 에 저장한다 (정규화 포기, 전체 일괄 로딩 + 가변 길이 대응).
--   IMAGE_RESOURCE:
--     bucket_path      → image_file_path 로 개명 (이미지 파일 경로)
--     image_tag_path   추가 (태그 JSON 경로, 선택)
--     image_hint_path  추가 (힌트 JSON 경로, 선택)
--   Object Storage 키 규약: images/{image_id}/{image_id}.jpg
--                           images/{image_id}/{image_id}.tags.json
--                           images/{image_id}/{image_id}.hint.json
--   게임 모드(DESCRIBE/CHOOSE)는 컬럼으로 강제하지 않음 —
--   각 경로의 NULL 여부로 판단 (file=DESCRIBE+CHOOSE 공용 이미지)
-- ============================================================

-- -----------------------------------------------------------
-- IMAGE_RESOURCE
-- OCI Object Storage 메타데이터만 저장, 실제 파일은 업로드 시 SDK가 관리
-- -----------------------------------------------------------
CREATE TABLE speechapp_content.image_resource (
    image_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_name      VARCHAR2(200) NOT NULL,
    image_file_path VARCHAR2(500) NOT NULL,
    image_tag_path  VARCHAR2(500) NULL,
    image_hint_path VARCHAR2(500) NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------
-- IMAGE_THEMA
-- 이미지가 어떤 테마에서 사용될 수 있는지 매핑
-- v4 (2026-09-02): IMAGE_THEMA 테이블 신설
-- -----------------------------------------------------------
CREATE TABLE speechapp_content.image_thema (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id    NUMBER(19) NOT NULL,
    thema_key   VARCHAR2(30) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_image_thema_image_id
        FOREIGN KEY (image_id) REFERENCES speechapp_content.image_resource(image_id),
    CONSTRAINT chk_image_thema_key
        CHECK (thema_key IN ('TEST','HOSPITAL','CAFE')),
    CONSTRAINT uq_image_thema_image_key
        UNIQUE (image_id, thema_key)
);

CREATE INDEX idx_image_thema_image_id ON speechapp_content.image_thema(image_id);
CREATE INDEX idx_image_thema_thema_key ON speechapp_content.image_thema(thema_key);
