-- ============================================================
-- migrate_v1.8.sql
-- LIVE DB migration: P3-20 session/voice schema
-- 기존 데이터(APP_USER, USER_PROFILE, IMAGE_RESOURCE) 보존
-- 실행 계정: sys as sysdba (connected to XEPDB1)
-- ============================================================

-- -----------------------------------------------------------
-- 1. CONTENT_TYPE
-- -----------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE speechapp_user.content_type (
        type_code   VARCHAR2(20) PRIMARY KEY,
        type_name   VARCHAR2(50) NOT NULL,
        category    VARCHAR2(50),
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO speechapp_user.content_type (type_code, type_name, category) VALUES (''LISTEN'', ''듣기'', ''receptive'')';
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO speechapp_user.content_type (type_code, type_name, category) VALUES (''NAMING'', ''이름 맞추기'', ''productive'')';
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO speechapp_user.content_type (type_code, type_name, category) VALUES (''SHADOWING'', ''쉐도잉'', ''productive'')';
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO speechapp_user.content_type (type_code, type_name, category) VALUES (''SELF_TALK'', ''자기 대화'', ''productive'')';
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO speechapp_user.content_type (type_code, type_name, category) VALUES (''STORYTELLING'', ''스토리텔링'', ''productive'')';
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
END;
/

-- -----------------------------------------------------------
-- 2. SESSION (reserved word: quoted identifier)
-- -----------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE speechapp_user."SESSION" (
        id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id     NUMBER(19) NOT NULL,
        theme       VARCHAR2(30),
        status      VARCHAR2(20) DEFAULT ''IN_PROGRESS'',
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at  TIMESTAMP,
        CONSTRAINT fk_session_user_id
            FOREIGN KEY (user_id) REFERENCES speechapp_user.app_user(id)
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_session_user_id ON speechapp_user."SESSION"(user_id)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- -----------------------------------------------------------
-- 3. TURN
-- -----------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE speechapp_user.turn (
        id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id      NUMBER(19) NOT NULL,
        turn_number     NUMBER(5) NOT NULL,
        content_type    VARCHAR2(20) NOT NULL,
        prompt_text     CLOB,
        choices_json    CLOB,
        correct_value   VARCHAR2(255),
        selected_value  VARCHAR2(255),
        answer_text     CLOB,
        hints_shown     NUMBER(1),
        created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_turn_session_id
            FOREIGN KEY (session_id) REFERENCES speechapp_user."SESSION"(id),
        CONSTRAINT fk_turn_content_type
            FOREIGN KEY (content_type) REFERENCES speechapp_user.content_type(type_code),
        CONSTRAINT chk_turn_content_type
            CHECK (content_type IN (''LISTEN'',''NAMING'',''SHADOWING'',''SELF_TALK'',''STORYTELLING'')),
        CONSTRAINT chk_turn_listen
            CHECK (
                (content_type != ''LISTEN'')
                OR (choices_json IS NOT NULL AND correct_value IS NOT NULL)
            ),
        CONSTRAINT chk_turn_naming
            CHECK (
                (content_type != ''NAMING'')
                OR (correct_value IS NOT NULL)
            )
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_turn_session_turn_number ON speechapp_user.turn(session_id, turn_number)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- -----------------------------------------------------------
-- 4. TURN_IMAGE
-- -----------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE speechapp_user.turn_image (
        turn_id      NUMBER(19) NOT NULL,
        image_id     NUMBER(19) NOT NULL,
        image_order  NUMBER(2) NOT NULL,
        PRIMARY KEY (turn_id, image_id),
        CONSTRAINT fk_turn_image_turn_id
            FOREIGN KEY (turn_id) REFERENCES speechapp_user.turn(id),
        CONSTRAINT fk_turn_image_image_id
            FOREIGN KEY (image_id) REFERENCES speechapp_content.image_resource(image_id),
        CONSTRAINT uq_turn_image_order
            UNIQUE (turn_id, image_order)
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- -----------------------------------------------------------
-- 5. VOICE_RECORD
-- TODO: response_time 단위 미결 (nullable)
-- TODO: LISTEN 선택값 표현 미결 (nullable)
-- TODO: 이미지널한 타입 미결 (nullable)
-- -----------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE speechapp_user.voice_record (
        id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id           NUMBER(19) NOT NULL,
        session_id        NUMBER(19) NOT NULL,
        turn_id           NUMBER(19) NOT NULL,
        speaker           VARCHAR2(10) NOT NULL,
        voice_file_path   VARCHAR2(500) NOT NULL,
        duration_seconds  NUMBER(5),
        syllables         NUMBER,
        response_time     NUMBER,
        articulation_rate NUMBER,
        created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_voice_record_user_id
            FOREIGN KEY (user_id) REFERENCES speechapp_user.app_user(id),
        CONSTRAINT fk_voice_record_session_id
            FOREIGN KEY (session_id) REFERENCES speechapp_user."SESSION"(id),
        CONSTRAINT fk_voice_record_turn_id
            FOREIGN KEY (turn_id) REFERENCES speechapp_user.turn(id),
        CONSTRAINT chk_voice_record_speaker
            CHECK (speaker IN (''USER'',''AI'')),
        CONSTRAINT uq_voice_record_turn_speaker
            UNIQUE (turn_id, speaker),
        CONSTRAINT chk_voice_record_ai
            CHECK (
                speaker != ''AI''
                OR (syllables IS NULL AND response_time IS NULL AND articulation_rate IS NULL)
            )
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_voice_record_session_id ON speechapp_user.voice_record(session_id)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_voice_record_turn_id ON speechapp_user.voice_record(turn_id)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- -----------------------------------------------------------
-- 6. GRANTS
-- -----------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON speechapp_user.content_type   TO speechapp_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON speechapp_user."SESSION"        TO speechapp_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON speechapp_user.turn           TO speechapp_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON speechapp_user.turn_image     TO speechapp_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON speechapp_user.voice_record   TO speechapp_app;

GRANT SELECT, REFERENCES ON speechapp_content.image_resource TO speechapp_user;

GRANT ALL ON speechapp_user.content_type   TO speechapp_admin;
GRANT ALL ON speechapp_user."SESSION"        TO speechapp_admin;
GRANT ALL ON speechapp_user.turn           TO speechapp_admin;
GRANT ALL ON speechapp_user.turn_image     TO speechapp_admin;
GRANT ALL ON speechapp_user.voice_record   TO speechapp_admin;

COMMIT;
